spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: file:./app/
cds:
  datasource.auto-config.enabled: false
  security:
    mock:
      users:
        - name: wayne
          password: pass_wayne
          additional:
            firstName: wayne
            lastName: tsui
            email: wayne_tsui@mail.com
        - name: mia
          password: pass_mia
          additional:
            firstName: Mia
            lastName: Bonnellac
            email: Mia.Bonnellac@mail.com3
        - name: sabine
          password: pass_sabine
          roles:
            - Administrators
          additional:
            firstName: Sabine
            lastName: Autumnpike
            email: Sabine.Autumnpike@mail.com
